package com.dcits.validation.service.utils;

import com.dcits.validation.entity.RbBusRestraints;
import com.dcits.validation.entity.RbBusRestraintsExample;
import com.dcits.validation.facade.eo.RbBusRestraintsEO;
import com.dcits.validation.enums.ThawDocumentType2;
import com.dcits.validation.enums.TranBranch;
import com.dcits.validation.enums.ThawDocumentType2;
import com.dcits.validation.enums.ThawDocumentType2;
import com.dcits.validation.enums.SourceModule;
import com.dcits.validation.enums.ThawDocumentType2;
import com.dcits.validation.enums.ThawDocumentType2;
import com.dcits.validation.enums.RestraintLevel;
import com.dcits.validation.enums.TermType;
import com.dcits.validation.enums.ThawDocumentType2;
import com.dcits.validation.enums.RestraintType;
import com.dcits.validation.enums.ThawDocumentType2;
import com.dcits.validation.enums.AcctInternalKeyType;
import com.dcits.validation.enums.ResAcctRange;
import com.dcits.validation.enums.RestraintSource;
import com.dcits.validation.enums.ThawDocumentType2;
import com.dcits.validation.enums.RestraintsStatus;

public final class RbBusRestraintsValueUtil {
    private RbBusRestraintsValueUtil() {
    }

    public static RbBusRestraintsEO entityToEo(RbBusRestraints entity) {
        if (entity == null) {
            return null;
        }
        RbBusRestraintsEO eo = new RbBusRestraintsEO();
        eo.setThawOthDocumentId2(entity.getThawOthDocumentId2());
        eo.setThawDocumentType2(ThawDocumentType2.byValue(entity.getThawDocumentType2()));
        eo.setDeductionJudiciaryName(entity.getDeductionJudiciaryName());
        eo.setLastUpdTimestamp(entity.getLastUpdTimestamp());
        eo.setTranBranch(TranBranch.byValue(entity.getTranBranch()));
        eo.setTerm(entity.getTerm());
        eo.setJudiciaryDocumentType2(ThawDocumentType2.byValue(entity.getJudiciaryDocumentType2()));
        eo.setResLawNo(entity.getResLawNo());
        eo.setStartDate(entity.getStartDate());
        eo.setTranAmt(entity.getTranAmt());
        eo.setJudiciaryOthDocumentId2(entity.getJudiciaryOthDocumentId2());
        eo.setCollatInd(entity.getCollatInd());
        eo.setJudiciaryDocumentType(ThawDocumentType2.byValue(entity.getJudiciaryDocumentType()));
        eo.setInternalKey(entity.getInternalKey());
        eo.setAuthUserId(entity.getAuthUserId());
        eo.setUserId(entity.getUserId());
        eo.setSourceModule(SourceModule.byValue(entity.getSourceModule()));
        eo.setRestraintJudiciaryName(entity.getRestraintJudiciaryName());
        eo.setThawOthDocumentType(ThawDocumentType2.byValue(entity.getThawOthDocumentType()));
        eo.setSettlementDate(entity.getSettlementDate());
        eo.setThawOthOfficerName(entity.getThawOthOfficerName());
        eo.setJudiciaryOthDocumentType2(ThawDocumentType2.byValue(entity.getJudiciaryOthDocumentType2()));
        eo.setReleaseLawNo(entity.getReleaseLawNo());
        eo.setRestraintLevel(RestraintLevel.byValue(entity.getRestraintLevel()));
        eo.setRestraintEndTime(entity.getRestraintEndTime());
        eo.setDeductionLawType(entity.getDeductionLawType());
        eo.setTermType(TermType.byValue(entity.getTermType()));
        eo.setResSeqNo(entity.getResSeqNo());
        eo.setPreFrozenFlag(entity.getPreFrozenFlag());
        eo.setJudiciaryOthDocumentId(entity.getJudiciaryOthDocumentId());
        eo.setThawDocumentType(ThawDocumentType2.byValue(entity.getThawDocumentType()));
        eo.setChannelSeqNo(entity.getChannelSeqNo());
        eo.setJudiciaryDocumentId2(entity.getJudiciaryDocumentId2());
        eo.setRestraintType(RestraintType.byValue(entity.getRestraintType()));
        eo.setProgramId(entity.getProgramId());
        eo.setPledgedAmt(entity.getPledgedAmt());
        eo.setThawOthDocumentType2(ThawDocumentType2.byValue(entity.getThawOthDocumentType2()));
        eo.setJudiciaryDocumentId(entity.getJudiciaryDocumentId());
        eo.setJudiciaryOfficerName(entity.getJudiciaryOfficerName());
        eo.setOriginalApplicationId(entity.getOriginalApplicationId());
        eo.setAcctInternalKeyType(AcctInternalKeyType.byValue(entity.getAcctInternalKeyType()));
        eo.setBusinessApplicationId(entity.getBusinessApplicationId());
        eo.setResAcctRange(ResAcctRange.byValue(entity.getResAcctRange()));
        eo.setThawOthDocumentId(entity.getThawOthDocumentId());
        eo.setThawDocumentId2(entity.getThawDocumentId2());
        eo.setBaseAcctNo(entity.getBaseAcctNo());
        eo.setReversalFlag(entity.getReversalFlag());
        eo.setThawOfficerName(entity.getThawOfficerName());
        eo.setReleaseJudiciaryName(entity.getReleaseJudiciaryName());
        eo.setCreateTimestamp(entity.getCreateTimestamp());
        eo.setRestraintSource(RestraintSource.byValue(entity.getRestraintSource()));
        eo.setResPriority(entity.getResPriority());
        eo.setJudiciaryOthOfficerName(entity.getJudiciaryOthOfficerName());
        eo.setChannelDate(entity.getChannelDate());
        eo.setContinueFreezeFlag(entity.getContinueFreezeFlag());
        eo.setThawDocumentId(entity.getThawDocumentId());
        eo.setJudiciaryOthDocumentType(ThawDocumentType2.byValue(entity.getJudiciaryOthDocumentType()));
        eo.setDeductionLawNo(entity.getDeductionLawNo());
        eo.setAhBuFlag(entity.getAhBuFlag());
        eo.setWaitSeq(entity.getWaitSeq());
        eo.setReference(entity.getReference());
        eo.setRestraintsStatus(RestraintsStatus.byValue(entity.getRestraintsStatus()));
        eo.setCompany(entity.getCompany());
        eo.setTranDate(entity.getTranDate());
        eo.setEndDate(entity.getEndDate());
        return eo;
    }

    public static RbBusRestraints eoToEntity(RbBusRestraintsEO eo) {
        if (eo == null) {
            return null;
        }
        RbBusRestraints entity = new RbBusRestraints();
        entity.setThawOthDocumentId2(eo.getThawOthDocumentId2());
        entity.setThawDocumentType2(eo.getThawDocumentType2() == null ? null : eo.getThawDocumentType2().getValue());
        entity.setDeductionJudiciaryName(eo.getDeductionJudiciaryName());
        entity.setLastUpdTimestamp(eo.getLastUpdTimestamp());
        entity.setTranBranch(eo.getTranBranch() == null ? null : eo.getTranBranch().getValue());
        entity.setTerm(eo.getTerm());
        entity.setJudiciaryDocumentType2(eo.getJudiciaryDocumentType2() == null ? null : eo.getJudiciaryDocumentType2().getValue());
        entity.setResLawNo(eo.getResLawNo());
        entity.setStartDate(eo.getStartDate());
        entity.setTranAmt(eo.getTranAmt());
        entity.setJudiciaryOthDocumentId2(eo.getJudiciaryOthDocumentId2());
        entity.setCollatInd(eo.getCollatInd());
        entity.setJudiciaryDocumentType(eo.getJudiciaryDocumentType() == null ? null : eo.getJudiciaryDocumentType().getValue());
        entity.setInternalKey(eo.getInternalKey());
        entity.setAuthUserId(eo.getAuthUserId());
        entity.setUserId(eo.getUserId());
        entity.setSourceModule(eo.getSourceModule() == null ? null : eo.getSourceModule().getValue());
        entity.setRestraintJudiciaryName(eo.getRestraintJudiciaryName());
        entity.setThawOthDocumentType(eo.getThawOthDocumentType() == null ? null : eo.getThawOthDocumentType().getValue());
        entity.setSettlementDate(eo.getSettlementDate());
        entity.setThawOthOfficerName(eo.getThawOthOfficerName());
        entity.setJudiciaryOthDocumentType2(eo.getJudiciaryOthDocumentType2() == null ? null : eo.getJudiciaryOthDocumentType2().getValue());
        entity.setReleaseLawNo(eo.getReleaseLawNo());
        entity.setRestraintLevel(eo.getRestraintLevel() == null ? null : eo.getRestraintLevel().getValue());
        entity.setRestraintEndTime(eo.getRestraintEndTime());
        entity.setDeductionLawType(eo.getDeductionLawType());
        entity.setTermType(eo.getTermType() == null ? null : eo.getTermType().getValue());
        entity.setResSeqNo(eo.getResSeqNo());
        entity.setPreFrozenFlag(eo.getPreFrozenFlag());
        entity.setJudiciaryOthDocumentId(eo.getJudiciaryOthDocumentId());
        entity.setThawDocumentType(eo.getThawDocumentType() == null ? null : eo.getThawDocumentType().getValue());
        entity.setChannelSeqNo(eo.getChannelSeqNo());
        entity.setJudiciaryDocumentId2(eo.getJudiciaryDocumentId2());
        entity.setRestraintType(eo.getRestraintType() == null ? null : eo.getRestraintType().getValue());
        entity.setProgramId(eo.getProgramId());
        entity.setPledgedAmt(eo.getPledgedAmt());
        entity.setThawOthDocumentType2(eo.getThawOthDocumentType2() == null ? null : eo.getThawOthDocumentType2().getValue());
        entity.setJudiciaryDocumentId(eo.getJudiciaryDocumentId());
        entity.setJudiciaryOfficerName(eo.getJudiciaryOfficerName());
        entity.setOriginalApplicationId(eo.getOriginalApplicationId());
        entity.setAcctInternalKeyType(eo.getAcctInternalKeyType() == null ? null : eo.getAcctInternalKeyType().getValue());
        entity.setBusinessApplicationId(eo.getBusinessApplicationId());
        entity.setResAcctRange(eo.getResAcctRange() == null ? null : eo.getResAcctRange().getValue());
        entity.setThawOthDocumentId(eo.getThawOthDocumentId());
        entity.setThawDocumentId2(eo.getThawDocumentId2());
        entity.setBaseAcctNo(eo.getBaseAcctNo());
        entity.setReversalFlag(eo.getReversalFlag());
        entity.setThawOfficerName(eo.getThawOfficerName());
        entity.setReleaseJudiciaryName(eo.getReleaseJudiciaryName());
        entity.setCreateTimestamp(eo.getCreateTimestamp());
        entity.setRestraintSource(eo.getRestraintSource() == null ? null : eo.getRestraintSource().getValue());
        entity.setResPriority(eo.getResPriority());
        entity.setJudiciaryOthOfficerName(eo.getJudiciaryOthOfficerName());
        entity.setChannelDate(eo.getChannelDate());
        entity.setContinueFreezeFlag(eo.getContinueFreezeFlag());
        entity.setThawDocumentId(eo.getThawDocumentId());
        entity.setJudiciaryOthDocumentType(eo.getJudiciaryOthDocumentType() == null ? null : eo.getJudiciaryOthDocumentType().getValue());
        entity.setDeductionLawNo(eo.getDeductionLawNo());
        entity.setAhBuFlag(eo.getAhBuFlag());
        entity.setWaitSeq(eo.getWaitSeq());
        entity.setReference(eo.getReference());
        entity.setRestraintsStatus(eo.getRestraintsStatus() == null ? null : eo.getRestraintsStatus().getValue());
        entity.setCompany(eo.getCompany());
        entity.setTranDate(eo.getTranDate());
        entity.setEndDate(eo.getEndDate());
        return entity;
    }

    public static RbBusRestraintsExample eoToEntityExample(RbBusRestraintsEO eo) {
        if (eo == null) {
            return null;
        }
        RbBusRestraintsExample example = new RbBusRestraintsExample();
        RbBusRestraintsExample.Criteria criteria = example.createCriteria();
        if (eo.getThawOthDocumentId2() != null) criteria.andThawOthDocumentId2EqualTo(eo.getThawOthDocumentId2());
        if (eo.getThawDocumentType2() != null) criteria.andThawDocumentType2EqualTo(eo.getThawDocumentType2().getValue());
        if (eo.getDeductionJudiciaryName() != null) criteria.andDeductionJudiciaryNameEqualTo(eo.getDeductionJudiciaryName());
        if (eo.getLastUpdTimestamp() != null) criteria.andLastUpdTimestampEqualTo(eo.getLastUpdTimestamp());
        if (eo.getTranBranch() != null) criteria.andTranBranchEqualTo(eo.getTranBranch().getValue());
        if (eo.getTerm() != null) criteria.andTermEqualTo(eo.getTerm());
        if (eo.getJudiciaryDocumentType2() != null) criteria.andJudiciaryDocumentType2EqualTo(eo.getJudiciaryDocumentType2().getValue());
        if (eo.getResLawNo() != null) criteria.andResLawNoEqualTo(eo.getResLawNo());
        if (eo.getStartDate() != null) criteria.andStartDateEqualTo(eo.getStartDate());
        if (eo.getTranAmt() != null) criteria.andTranAmtEqualTo(eo.getTranAmt());
        if (eo.getJudiciaryOthDocumentId2() != null) criteria.andJudiciaryOthDocumentId2EqualTo(eo.getJudiciaryOthDocumentId2());
        if (eo.getCollatInd() != null) criteria.andCollatIndEqualTo(eo.getCollatInd());
        if (eo.getJudiciaryDocumentType() != null) criteria.andJudiciaryDocumentTypeEqualTo(eo.getJudiciaryDocumentType().getValue());
        if (eo.getInternalKey() != null) criteria.andInternalKeyEqualTo(eo.getInternalKey());
        if (eo.getAuthUserId() != null) criteria.andAuthUserIdEqualTo(eo.getAuthUserId());
        if (eo.getUserId() != null) criteria.andUserIdEqualTo(eo.getUserId());
        if (eo.getSourceModule() != null) criteria.andSourceModuleEqualTo(eo.getSourceModule().getValue());
        if (eo.getRestraintJudiciaryName() != null) criteria.andRestraintJudiciaryNameEqualTo(eo.getRestraintJudiciaryName());
        if (eo.getThawOthDocumentType() != null) criteria.andThawOthDocumentTypeEqualTo(eo.getThawOthDocumentType().getValue());
        if (eo.getSettlementDate() != null) criteria.andSettlementDateEqualTo(eo.getSettlementDate());
        if (eo.getThawOthOfficerName() != null) criteria.andThawOthOfficerNameEqualTo(eo.getThawOthOfficerName());
        if (eo.getJudiciaryOthDocumentType2() != null) criteria.andJudiciaryOthDocumentType2EqualTo(eo.getJudiciaryOthDocumentType2().getValue());
        if (eo.getReleaseLawNo() != null) criteria.andReleaseLawNoEqualTo(eo.getReleaseLawNo());
        if (eo.getRestraintLevel() != null) criteria.andRestraintLevelEqualTo(eo.getRestraintLevel().getValue());
        if (eo.getRestraintEndTime() != null) criteria.andRestraintEndTimeEqualTo(eo.getRestraintEndTime());
        if (eo.getDeductionLawType() != null) criteria.andDeductionLawTypeEqualTo(eo.getDeductionLawType());
        if (eo.getTermType() != null) criteria.andTermTypeEqualTo(eo.getTermType().getValue());
        if (eo.getResSeqNo() != null) criteria.andResSeqNoEqualTo(eo.getResSeqNo());
        if (eo.getPreFrozenFlag() != null) criteria.andPreFrozenFlagEqualTo(eo.getPreFrozenFlag());
        if (eo.getJudiciaryOthDocumentId() != null) criteria.andJudiciaryOthDocumentIdEqualTo(eo.getJudiciaryOthDocumentId());
        if (eo.getThawDocumentType() != null) criteria.andThawDocumentTypeEqualTo(eo.getThawDocumentType().getValue());
        if (eo.getChannelSeqNo() != null) criteria.andChannelSeqNoEqualTo(eo.getChannelSeqNo());
        if (eo.getJudiciaryDocumentId2() != null) criteria.andJudiciaryDocumentId2EqualTo(eo.getJudiciaryDocumentId2());
        if (eo.getRestraintType() != null) criteria.andRestraintTypeEqualTo(eo.getRestraintType().getValue());
        if (eo.getProgramId() != null) criteria.andProgramIdEqualTo(eo.getProgramId());
        if (eo.getPledgedAmt() != null) criteria.andPledgedAmtEqualTo(eo.getPledgedAmt());
        if (eo.getThawOthDocumentType2() != null) criteria.andThawOthDocumentType2EqualTo(eo.getThawOthDocumentType2().getValue());
        if (eo.getJudiciaryDocumentId() != null) criteria.andJudiciaryDocumentIdEqualTo(eo.getJudiciaryDocumentId());
        if (eo.getJudiciaryOfficerName() != null) criteria.andJudiciaryOfficerNameEqualTo(eo.getJudiciaryOfficerName());
        if (eo.getOriginalApplicationId() != null) criteria.andOriginalApplicationIdEqualTo(eo.getOriginalApplicationId());
        if (eo.getAcctInternalKeyType() != null) criteria.andAcctInternalKeyTypeEqualTo(eo.getAcctInternalKeyType().getValue());
        if (eo.getBusinessApplicationId() != null) criteria.andBusinessApplicationIdEqualTo(eo.getBusinessApplicationId());
        if (eo.getResAcctRange() != null) criteria.andResAcctRangeEqualTo(eo.getResAcctRange().getValue());
        if (eo.getThawOthDocumentId() != null) criteria.andThawOthDocumentIdEqualTo(eo.getThawOthDocumentId());
        if (eo.getThawDocumentId2() != null) criteria.andThawDocumentId2EqualTo(eo.getThawDocumentId2());
        if (eo.getBaseAcctNo() != null) criteria.andBaseAcctNoEqualTo(eo.getBaseAcctNo());
        if (eo.getReversalFlag() != null) criteria.andReversalFlagEqualTo(eo.getReversalFlag());
        if (eo.getThawOfficerName() != null) criteria.andThawOfficerNameEqualTo(eo.getThawOfficerName());
        if (eo.getReleaseJudiciaryName() != null) criteria.andReleaseJudiciaryNameEqualTo(eo.getReleaseJudiciaryName());
        if (eo.getCreateTimestamp() != null) criteria.andCreateTimestampEqualTo(eo.getCreateTimestamp());
        if (eo.getRestraintSource() != null) criteria.andRestraintSourceEqualTo(eo.getRestraintSource().getValue());
        if (eo.getResPriority() != null) criteria.andResPriorityEqualTo(eo.getResPriority());
        if (eo.getJudiciaryOthOfficerName() != null) criteria.andJudiciaryOthOfficerNameEqualTo(eo.getJudiciaryOthOfficerName());
        if (eo.getChannelDate() != null) criteria.andChannelDateEqualTo(eo.getChannelDate());
        if (eo.getContinueFreezeFlag() != null) criteria.andContinueFreezeFlagEqualTo(eo.getContinueFreezeFlag());
        if (eo.getThawDocumentId() != null) criteria.andThawDocumentIdEqualTo(eo.getThawDocumentId());
        if (eo.getJudiciaryOthDocumentType() != null) criteria.andJudiciaryOthDocumentTypeEqualTo(eo.getJudiciaryOthDocumentType().getValue());
        if (eo.getDeductionLawNo() != null) criteria.andDeductionLawNoEqualTo(eo.getDeductionLawNo());
        if (eo.getAhBuFlag() != null) criteria.andAhBuFlagEqualTo(eo.getAhBuFlag());
        if (eo.getWaitSeq() != null) criteria.andWaitSeqEqualTo(eo.getWaitSeq());
        if (eo.getReference() != null) criteria.andReferenceEqualTo(eo.getReference());
        if (eo.getRestraintsStatus() != null) criteria.andRestraintsStatusEqualTo(eo.getRestraintsStatus().getValue());
        if (eo.getCompany() != null) criteria.andCompanyEqualTo(eo.getCompany());
        if (eo.getTranDate() != null) criteria.andTranDateEqualTo(eo.getTranDate());
        if (eo.getEndDate() != null) criteria.andEndDateEqualTo(eo.getEndDate());
        return example;
    }
}