package com.dcits.validation.service.utils;

import com.dcits.validation.entity.RbBusAcct;
import com.dcits.validation.entity.RbBusAcctExample;
import com.dcits.validation.facade.eo.RbBusAcctEO;
import com.dcits.validation.enums.TermType;
import com.dcits.validation.enums.AllDraRange;
import com.dcits.validation.enums.DepositNature;
import com.dcits.validation.enums.AcctVerifyFlag;
import com.dcits.validation.enums.AcctNatureNo;
import com.dcits.validation.enums.FarmerFlag;
import com.dcits.validation.enums.ClientType;
import com.dcits.validation.enums.IntIndFlag;
import com.dcits.validation.enums.RbBusAcctPurpose;
import com.dcits.validation.enums.SimpleAcct;
import com.dcits.validation.enums.AutoRenewInd;
import com.dcits.validation.enums.AcctStatus;
import com.dcits.validation.enums.SpecAcctFlag;
import com.dcits.validation.enums.AcctStatus;
import com.dcits.validation.enums.TranBranch;
import com.dcits.validation.enums.TranBranch;
import com.dcits.validation.enums.AllDraRange;
import com.dcits.validation.enums.AcctCcy;
import com.dcits.validation.enums.RenewMethod;
import com.dcits.validation.enums.AcctRiskLevel;
import com.dcits.validation.enums.CheckCertificateType;
import com.dcits.validation.enums.ManageType;
import com.dcits.validation.enums.TermType;
import com.dcits.validation.enums.RbAcctType;
import com.dcits.validation.enums.SourceType;
import com.dcits.validation.enums.AnnualStatus;
import com.dcits.validation.enums.BalType;
import com.dcits.validation.enums.FixedCall;
import com.dcits.validation.enums.AcctVerifyResult;
import com.dcits.validation.enums.AllDepInd;
import com.dcits.validation.enums.OsaFlag;
import com.dcits.validation.enums.TranBranch;
import com.dcits.validation.enums.AllDraInd;

public final class RbBusAcctValueUtil {
    private RbBusAcctValueUtil() {
    }

    public static RbBusAcctEO entityToEo(RbBusAcct entity) {
        if (entity == null) {
            return null;
        }
        RbBusAcctEO eo = new RbBusAcctEO();
        eo.setCreateTimestamp(entity.getCreateTimestamp());
        eo.setClientNo(entity.getClientNo());
        eo.setAcctOpenDate(entity.getAcctOpenDate());
        eo.setTerm(entity.getTerm());
        eo.setAcctNameEn(entity.getAcctNameEn());
        eo.setFtaAcctFlag(entity.getFtaAcctFlag());
        eo.setTermType(TermType.byValue(entity.getTermType()));
        eo.setAllDraRange(AllDraRange.byValue(entity.getAllDraRange()));
        eo.setDepositNature(DepositNature.byValue(entity.getDepositNature()));
        eo.setAcctVerifyFlag(AcctVerifyFlag.byValue(entity.getAcctVerifyFlag()));
        eo.setAcctCloseDate(entity.getAcctCloseDate());
        eo.setAcctNatureNo(AcctNatureNo.byValue(entity.getAcctNatureNo()));
        eo.setFarmerFlag(FarmerFlag.byValue(entity.getFarmerFlag()));
        eo.setAnnualDate(entity.getAnnualDate());
        eo.setLastTranDate(entity.getLastTranDate());
        eo.setRolloverNo(entity.getRolloverNo());
        eo.setClientType(ClientType.byValue(entity.getClientType()));
        eo.setLastUpdTimestamp(entity.getLastUpdTimestamp());
        eo.setRecoverFlag(entity.getRecoverFlag());
        eo.setAutoRenewTerm(entity.getAutoRenewTerm());
        eo.setAcctName(entity.getAcctName());
        eo.setLeadAcctFlag(entity.getLeadAcctFlag());
        eo.setFtaNo(entity.getFtaNo());
        eo.setProdNo(entity.getProdNo());
        eo.setIntIndFlag(IntIndFlag.byValue(entity.getIntIndFlag()));
        eo.setCycleIntFlag(entity.getCycleIntFlag());
        eo.setAllowSuspendFlag(entity.getAllowSuspendFlag());
        eo.setRbBusAcctPurpose(RbBusAcctPurpose.byValue(entity.getRbBusAcctPurpose()));
        eo.setCollatInd(entity.getCollatInd());
        eo.setFirstDrawDate(entity.getFirstDrawDate());
        eo.setAutoDep(entity.getAutoDep());
        eo.setSimpleAcct(SimpleAcct.byValue(entity.getSimpleAcct()));
        eo.setTaxRate(entity.getTaxRate());
        eo.setIntTaxLevy(entity.getIntTaxLevy());
        eo.setAcctExecName(entity.getAcctExecName());
        eo.setAcctDueDate(entity.getAcctDueDate());
        eo.setApprLetterNo(entity.getApprLetterNo());
        eo.setAutoRenewInd(AutoRenewInd.byValue(entity.getAutoRenewInd()));
        eo.setManageContent(entity.getManageContent());
        eo.setAcctStatus(AcctStatus.byValue(entity.getAcctStatus()));
        eo.setSpecAcctFlag(SpecAcctFlag.byValue(entity.getSpecAcctFlag()));
        eo.setAcctStatusPrev(AcctStatus.byValue(entity.getAcctStatusPrev()));
        eo.setAcctBranch(TranBranch.byValue(entity.getAcctBranch()));
        eo.setHomeBranch(TranBranch.byValue(entity.getHomeBranch()));
        eo.setIsAllowClose(entity.getIsAllowClose());
        eo.setTimesRolledover(entity.getTimesRolledover());
        eo.setLastResetDate(entity.getLastResetDate());
        eo.setDormantDate(entity.getDormantDate());
        eo.setRenewNo(entity.getRenewNo());
        eo.setAllDepRange(AllDraRange.byValue(entity.getAllDepRange()));
        eo.setAcctCcy(AcctCcy.byValue(entity.getAcctCcy()));
        eo.setCardNo(entity.getCardNo());
        eo.setLastStopDate(entity.getLastStopDate());
        eo.setSecretAcct(entity.getSecretAcct());
        eo.setRenewMethod(RenewMethod.byValue(entity.getRenewMethod()));
        eo.setManageFlag(entity.getManageFlag());
        eo.setAcctRiskLevel(AcctRiskLevel.byValue(entity.getAcctRiskLevel()));
        eo.setCheckCertificateAmt(entity.getCheckCertificateAmt());
        eo.setIsSellCheque(entity.getIsSellCheque());
        eo.setCheckCertificateType(CheckCertificateType.byValue(entity.getCheckCertificateType()));
        eo.setManageType(ManageType.byValue(entity.getManageType()));
        eo.setPromoterName(entity.getPromoterName());
        eo.setPromoterCode(entity.getPromoterCode());
        eo.setTermLack(entity.getTermLack());
        eo.setAutoRenewTermType(TermType.byValue(entity.getAutoRenewTermType()));
        eo.setRbAcctType(RbAcctType.byValue(entity.getRbAcctType()));
        eo.setEffectDate(entity.getEffectDate());
        eo.setTimesRenewed(entity.getTimesRenewed());
        eo.setAnnualFlag(entity.getAnnualFlag());
        eo.setAcctExecCode(entity.getAcctExecCode());
        eo.setAcctRealFlag(entity.getAcctRealFlag());
        eo.setDepMaturityDate(entity.getDepMaturityDate());
        eo.setSourceType(SourceType.byValue(entity.getSourceType()));
        eo.setTotalDrawAmt(entity.getTotalDrawAmt());
        eo.setJointAcctFlag(entity.getJointAcctFlag());
        eo.setBaseAcctNo(entity.getBaseAcctNo());
        eo.setAnnualStatus(AnnualStatus.byValue(entity.getAnnualStatus()));
        eo.setBalType(BalType.byValue(entity.getBalType()));
        eo.setManagementFreeFlag(entity.getManagementFreeFlag());
        eo.setAcctLicenseDate(entity.getAcctLicenseDate());
        eo.setAcctStopPay(entity.getAcctStopPay());
        eo.setLoanFundFlag(entity.getLoanFundFlag());
        eo.setImpoundFad(entity.getImpoundFad());
        eo.setAcctResStatus(entity.getAcctResStatus());
        eo.setAcctLicenseNo(entity.getAcctLicenseNo());
        eo.setParentInternalKey(entity.getParentInternalKey());
        eo.setTaxDiscountMaturityDate(entity.getTaxDiscountMaturityDate());
        eo.setFixedCall(FixedCall.byValue(entity.getFixedCall()));
        eo.setAcctVerifyResult(AcctVerifyResult.byValue(entity.getAcctVerifyResult()));
        eo.setAllDepInd(AllDepInd.byValue(entity.getAllDepInd()));
        eo.setOsaFlag(OsaFlag.byValue(entity.getOsaFlag()));
        eo.setCaseInvolvedFlag(entity.getCaseInvolvedFlag());
        eo.setAllDraIntBranch(TranBranch.byValue(entity.getAllDraIntBranch()));
        eo.setPartialRenewRoll(entity.getPartialRenewRoll());
        eo.setAutoSettleFlag(entity.getAutoSettleFlag());
        eo.setAllDraInd(AllDraInd.byValue(entity.getAllDraInd()));
        eo.setLineOwnerShip(entity.getLineOwnerShip());
        eo.setInternalKey(entity.getInternalKey());
        eo.setAcctCloseReason(entity.getAcctCloseReason());
        return eo;
    }

    public static RbBusAcct eoToEntity(RbBusAcctEO eo) {
        if (eo == null) {
            return null;
        }
        RbBusAcct entity = new RbBusAcct();
        entity.setCreateTimestamp(eo.getCreateTimestamp());
        entity.setClientNo(eo.getClientNo());
        entity.setAcctOpenDate(eo.getAcctOpenDate());
        entity.setTerm(eo.getTerm());
        entity.setAcctNameEn(eo.getAcctNameEn());
        entity.setFtaAcctFlag(eo.getFtaAcctFlag());
        entity.setTermType(eo.getTermType() == null ? null : eo.getTermType().getValue());
        entity.setAllDraRange(eo.getAllDraRange() == null ? null : eo.getAllDraRange().getValue());
        entity.setDepositNature(eo.getDepositNature() == null ? null : eo.getDepositNature().getValue());
        entity.setAcctVerifyFlag(eo.getAcctVerifyFlag() == null ? null : eo.getAcctVerifyFlag().getValue());
        entity.setAcctCloseDate(eo.getAcctCloseDate());
        entity.setAcctNatureNo(eo.getAcctNatureNo() == null ? null : eo.getAcctNatureNo().getValue());
        entity.setFarmerFlag(eo.getFarmerFlag() == null ? null : eo.getFarmerFlag().getValue());
        entity.setAnnualDate(eo.getAnnualDate());
        entity.setLastTranDate(eo.getLastTranDate());
        entity.setRolloverNo(eo.getRolloverNo());
        entity.setClientType(eo.getClientType() == null ? null : eo.getClientType().getValue());
        entity.setLastUpdTimestamp(eo.getLastUpdTimestamp());
        entity.setRecoverFlag(eo.getRecoverFlag());
        entity.setAutoRenewTerm(eo.getAutoRenewTerm());
        entity.setAcctName(eo.getAcctName());
        entity.setLeadAcctFlag(eo.getLeadAcctFlag());
        entity.setFtaNo(eo.getFtaNo());
        entity.setProdNo(eo.getProdNo());
        entity.setIntIndFlag(eo.getIntIndFlag() == null ? null : eo.getIntIndFlag().getValue());
        entity.setCycleIntFlag(eo.getCycleIntFlag());
        entity.setAllowSuspendFlag(eo.getAllowSuspendFlag());
        entity.setRbBusAcctPurpose(eo.getRbBusAcctPurpose() == null ? null : eo.getRbBusAcctPurpose().getValue());
        entity.setCollatInd(eo.getCollatInd());
        entity.setFirstDrawDate(eo.getFirstDrawDate());
        entity.setAutoDep(eo.getAutoDep());
        entity.setSimpleAcct(eo.getSimpleAcct() == null ? null : eo.getSimpleAcct().getValue());
        entity.setTaxRate(eo.getTaxRate());
        entity.setIntTaxLevy(eo.getIntTaxLevy());
        entity.setAcctExecName(eo.getAcctExecName());
        entity.setAcctDueDate(eo.getAcctDueDate());
        entity.setApprLetterNo(eo.getApprLetterNo());
        entity.setAutoRenewInd(eo.getAutoRenewInd() == null ? null : eo.getAutoRenewInd().getValue());
        entity.setManageContent(eo.getManageContent());
        entity.setAcctStatus(eo.getAcctStatus() == null ? null : eo.getAcctStatus().getValue());
        entity.setSpecAcctFlag(eo.getSpecAcctFlag() == null ? null : eo.getSpecAcctFlag().getValue());
        entity.setAcctStatusPrev(eo.getAcctStatusPrev() == null ? null : eo.getAcctStatusPrev().getValue());
        entity.setAcctBranch(eo.getAcctBranch() == null ? null : eo.getAcctBranch().getValue());
        entity.setHomeBranch(eo.getHomeBranch() == null ? null : eo.getHomeBranch().getValue());
        entity.setIsAllowClose(eo.getIsAllowClose());
        entity.setTimesRolledover(eo.getTimesRolledover());
        entity.setLastResetDate(eo.getLastResetDate());
        entity.setDormantDate(eo.getDormantDate());
        entity.setRenewNo(eo.getRenewNo());
        entity.setAllDepRange(eo.getAllDepRange() == null ? null : eo.getAllDepRange().getValue());
        entity.setAcctCcy(eo.getAcctCcy() == null ? null : eo.getAcctCcy().getValue());
        entity.setCardNo(eo.getCardNo());
        entity.setLastStopDate(eo.getLastStopDate());
        entity.setSecretAcct(eo.getSecretAcct());
        entity.setRenewMethod(eo.getRenewMethod() == null ? null : eo.getRenewMethod().getValue());
        entity.setManageFlag(eo.getManageFlag());
        entity.setAcctRiskLevel(eo.getAcctRiskLevel() == null ? null : eo.getAcctRiskLevel().getValue());
        entity.setCheckCertificateAmt(eo.getCheckCertificateAmt());
        entity.setIsSellCheque(eo.getIsSellCheque());
        entity.setCheckCertificateType(eo.getCheckCertificateType() == null ? null : eo.getCheckCertificateType().getValue());
        entity.setManageType(eo.getManageType() == null ? null : eo.getManageType().getValue());
        entity.setPromoterName(eo.getPromoterName());
        entity.setPromoterCode(eo.getPromoterCode());
        entity.setTermLack(eo.getTermLack());
        entity.setAutoRenewTermType(eo.getAutoRenewTermType() == null ? null : eo.getAutoRenewTermType().getValue());
        entity.setRbAcctType(eo.getRbAcctType() == null ? null : eo.getRbAcctType().getValue());
        entity.setEffectDate(eo.getEffectDate());
        entity.setTimesRenewed(eo.getTimesRenewed());
        entity.setAnnualFlag(eo.getAnnualFlag());
        entity.setAcctExecCode(eo.getAcctExecCode());
        entity.setAcctRealFlag(eo.getAcctRealFlag());
        entity.setDepMaturityDate(eo.getDepMaturityDate());
        entity.setSourceType(eo.getSourceType() == null ? null : eo.getSourceType().getValue());
        entity.setTotalDrawAmt(eo.getTotalDrawAmt());
        entity.setJointAcctFlag(eo.getJointAcctFlag());
        entity.setBaseAcctNo(eo.getBaseAcctNo());
        entity.setAnnualStatus(eo.getAnnualStatus() == null ? null : eo.getAnnualStatus().getValue());
        entity.setBalType(eo.getBalType() == null ? null : eo.getBalType().getValue());
        entity.setManagementFreeFlag(eo.getManagementFreeFlag());
        entity.setAcctLicenseDate(eo.getAcctLicenseDate());
        entity.setAcctStopPay(eo.getAcctStopPay());
        entity.setLoanFundFlag(eo.getLoanFundFlag());
        entity.setImpoundFad(eo.getImpoundFad());
        entity.setAcctResStatus(eo.getAcctResStatus());
        entity.setAcctLicenseNo(eo.getAcctLicenseNo());
        entity.setParentInternalKey(eo.getParentInternalKey());
        entity.setTaxDiscountMaturityDate(eo.getTaxDiscountMaturityDate());
        entity.setFixedCall(eo.getFixedCall() == null ? null : eo.getFixedCall().getValue());
        entity.setAcctVerifyResult(eo.getAcctVerifyResult() == null ? null : eo.getAcctVerifyResult().getValue());
        entity.setAllDepInd(eo.getAllDepInd() == null ? null : eo.getAllDepInd().getValue());
        entity.setOsaFlag(eo.getOsaFlag() == null ? null : eo.getOsaFlag().getValue());
        entity.setCaseInvolvedFlag(eo.getCaseInvolvedFlag());
        entity.setAllDraIntBranch(eo.getAllDraIntBranch() == null ? null : eo.getAllDraIntBranch().getValue());
        entity.setPartialRenewRoll(eo.getPartialRenewRoll());
        entity.setAutoSettleFlag(eo.getAutoSettleFlag());
        entity.setAllDraInd(eo.getAllDraInd() == null ? null : eo.getAllDraInd().getValue());
        entity.setLineOwnerShip(eo.getLineOwnerShip());
        entity.setInternalKey(eo.getInternalKey());
        entity.setAcctCloseReason(eo.getAcctCloseReason());
        return entity;
    }

    public static RbBusAcctExample eoToEntityExample(RbBusAcctEO eo) {
        if (eo == null) {
            return null;
        }
        RbBusAcctExample example = new RbBusAcctExample();
        RbBusAcctExample.Criteria criteria = example.createCriteria();
        if (eo.getCreateTimestamp() != null) criteria.andCreateTimestampEqualTo(eo.getCreateTimestamp());
        if (eo.getClientNo() != null) criteria.andClientNoEqualTo(eo.getClientNo());
        if (eo.getAcctOpenDate() != null) criteria.andAcctOpenDateEqualTo(eo.getAcctOpenDate());
        if (eo.getTerm() != null) criteria.andTermEqualTo(eo.getTerm());
        if (eo.getAcctNameEn() != null) criteria.andAcctNameEnEqualTo(eo.getAcctNameEn());
        if (eo.getFtaAcctFlag() != null) criteria.andFtaAcctFlagEqualTo(eo.getFtaAcctFlag());
        if (eo.getTermType() != null) criteria.andTermTypeEqualTo(eo.getTermType().getValue());
        if (eo.getAllDraRange() != null) criteria.andAllDraRangeEqualTo(eo.getAllDraRange().getValue());
        if (eo.getDepositNature() != null) criteria.andDepositNatureEqualTo(eo.getDepositNature().getValue());
        if (eo.getAcctVerifyFlag() != null) criteria.andAcctVerifyFlagEqualTo(eo.getAcctVerifyFlag().getValue());
        if (eo.getAcctCloseDate() != null) criteria.andAcctCloseDateEqualTo(eo.getAcctCloseDate());
        if (eo.getAcctNatureNo() != null) criteria.andAcctNatureNoEqualTo(eo.getAcctNatureNo().getValue());
        if (eo.getFarmerFlag() != null) criteria.andFarmerFlagEqualTo(eo.getFarmerFlag().getValue());
        if (eo.getAnnualDate() != null) criteria.andAnnualDateEqualTo(eo.getAnnualDate());
        if (eo.getLastTranDate() != null) criteria.andLastTranDateEqualTo(eo.getLastTranDate());
        if (eo.getRolloverNo() != null) criteria.andRolloverNoEqualTo(eo.getRolloverNo());
        if (eo.getClientType() != null) criteria.andClientTypeEqualTo(eo.getClientType().getValue());
        if (eo.getLastUpdTimestamp() != null) criteria.andLastUpdTimestampEqualTo(eo.getLastUpdTimestamp());
        if (eo.getRecoverFlag() != null) criteria.andRecoverFlagEqualTo(eo.getRecoverFlag());
        if (eo.getAutoRenewTerm() != null) criteria.andAutoRenewTermEqualTo(eo.getAutoRenewTerm());
        if (eo.getAcctName() != null) criteria.andAcctNameEqualTo(eo.getAcctName());
        if (eo.getLeadAcctFlag() != null) criteria.andLeadAcctFlagEqualTo(eo.getLeadAcctFlag());
        if (eo.getFtaNo() != null) criteria.andFtaNoEqualTo(eo.getFtaNo());
        if (eo.getProdNo() != null) criteria.andProdNoEqualTo(eo.getProdNo());
        if (eo.getIntIndFlag() != null) criteria.andIntIndFlagEqualTo(eo.getIntIndFlag().getValue());
        if (eo.getCycleIntFlag() != null) criteria.andCycleIntFlagEqualTo(eo.getCycleIntFlag());
        if (eo.getAllowSuspendFlag() != null) criteria.andAllowSuspendFlagEqualTo(eo.getAllowSuspendFlag());
        if (eo.getRbBusAcctPurpose() != null) criteria.andRbBusAcctPurposeEqualTo(eo.getRbBusAcctPurpose().getValue());
        if (eo.getCollatInd() != null) criteria.andCollatIndEqualTo(eo.getCollatInd());
        if (eo.getFirstDrawDate() != null) criteria.andFirstDrawDateEqualTo(eo.getFirstDrawDate());
        if (eo.getAutoDep() != null) criteria.andAutoDepEqualTo(eo.getAutoDep());
        if (eo.getSimpleAcct() != null) criteria.andSimpleAcctEqualTo(eo.getSimpleAcct().getValue());
        if (eo.getTaxRate() != null) criteria.andTaxRateEqualTo(eo.getTaxRate());
        if (eo.getIntTaxLevy() != null) criteria.andIntTaxLevyEqualTo(eo.getIntTaxLevy());
        if (eo.getAcctExecName() != null) criteria.andAcctExecNameEqualTo(eo.getAcctExecName());
        if (eo.getAcctDueDate() != null) criteria.andAcctDueDateEqualTo(eo.getAcctDueDate());
        if (eo.getApprLetterNo() != null) criteria.andApprLetterNoEqualTo(eo.getApprLetterNo());
        if (eo.getAutoRenewInd() != null) criteria.andAutoRenewIndEqualTo(eo.getAutoRenewInd().getValue());
        if (eo.getManageContent() != null) criteria.andManageContentEqualTo(eo.getManageContent());
        if (eo.getAcctStatus() != null) criteria.andAcctStatusEqualTo(eo.getAcctStatus().getValue());
        if (eo.getSpecAcctFlag() != null) criteria.andSpecAcctFlagEqualTo(eo.getSpecAcctFlag().getValue());
        if (eo.getAcctStatusPrev() != null) criteria.andAcctStatusPrevEqualTo(eo.getAcctStatusPrev().getValue());
        if (eo.getAcctBranch() != null) criteria.andAcctBranchEqualTo(eo.getAcctBranch().getValue());
        if (eo.getHomeBranch() != null) criteria.andHomeBranchEqualTo(eo.getHomeBranch().getValue());
        if (eo.getIsAllowClose() != null) criteria.andIsAllowCloseEqualTo(eo.getIsAllowClose());
        if (eo.getTimesRolledover() != null) criteria.andTimesRolledoverEqualTo(eo.getTimesRolledover());
        if (eo.getLastResetDate() != null) criteria.andLastResetDateEqualTo(eo.getLastResetDate());
        if (eo.getDormantDate() != null) criteria.andDormantDateEqualTo(eo.getDormantDate());
        if (eo.getRenewNo() != null) criteria.andRenewNoEqualTo(eo.getRenewNo());
        if (eo.getAllDepRange() != null) criteria.andAllDepRangeEqualTo(eo.getAllDepRange().getValue());
        if (eo.getAcctCcy() != null) criteria.andAcctCcyEqualTo(eo.getAcctCcy().getValue());
        if (eo.getCardNo() != null) criteria.andCardNoEqualTo(eo.getCardNo());
        if (eo.getLastStopDate() != null) criteria.andLastStopDateEqualTo(eo.getLastStopDate());
        if (eo.getSecretAcct() != null) criteria.andSecretAcctEqualTo(eo.getSecretAcct());
        if (eo.getRenewMethod() != null) criteria.andRenewMethodEqualTo(eo.getRenewMethod().getValue());
        if (eo.getManageFlag() != null) criteria.andManageFlagEqualTo(eo.getManageFlag());
        if (eo.getAcctRiskLevel() != null) criteria.andAcctRiskLevelEqualTo(eo.getAcctRiskLevel().getValue());
        if (eo.getCheckCertificateAmt() != null) criteria.andCheckCertificateAmtEqualTo(eo.getCheckCertificateAmt());
        if (eo.getIsSellCheque() != null) criteria.andIsSellChequeEqualTo(eo.getIsSellCheque());
        if (eo.getCheckCertificateType() != null) criteria.andCheckCertificateTypeEqualTo(eo.getCheckCertificateType().getValue());
        if (eo.getManageType() != null) criteria.andManageTypeEqualTo(eo.getManageType().getValue());
        if (eo.getPromoterName() != null) criteria.andPromoterNameEqualTo(eo.getPromoterName());
        if (eo.getPromoterCode() != null) criteria.andPromoterCodeEqualTo(eo.getPromoterCode());
        if (eo.getTermLack() != null) criteria.andTermLackEqualTo(eo.getTermLack());
        if (eo.getAutoRenewTermType() != null) criteria.andAutoRenewTermTypeEqualTo(eo.getAutoRenewTermType().getValue());
        if (eo.getRbAcctType() != null) criteria.andRbAcctTypeEqualTo(eo.getRbAcctType().getValue());
        if (eo.getEffectDate() != null) criteria.andEffectDateEqualTo(eo.getEffectDate());
        if (eo.getTimesRenewed() != null) criteria.andTimesRenewedEqualTo(eo.getTimesRenewed());
        if (eo.getAnnualFlag() != null) criteria.andAnnualFlagEqualTo(eo.getAnnualFlag());
        if (eo.getAcctExecCode() != null) criteria.andAcctExecCodeEqualTo(eo.getAcctExecCode());
        if (eo.getAcctRealFlag() != null) criteria.andAcctRealFlagEqualTo(eo.getAcctRealFlag());
        if (eo.getDepMaturityDate() != null) criteria.andDepMaturityDateEqualTo(eo.getDepMaturityDate());
        if (eo.getSourceType() != null) criteria.andSourceTypeEqualTo(eo.getSourceType().getValue());
        if (eo.getTotalDrawAmt() != null) criteria.andTotalDrawAmtEqualTo(eo.getTotalDrawAmt());
        if (eo.getJointAcctFlag() != null) criteria.andJointAcctFlagEqualTo(eo.getJointAcctFlag());
        if (eo.getBaseAcctNo() != null) criteria.andBaseAcctNoEqualTo(eo.getBaseAcctNo());
        if (eo.getAnnualStatus() != null) criteria.andAnnualStatusEqualTo(eo.getAnnualStatus().getValue());
        if (eo.getBalType() != null) criteria.andBalTypeEqualTo(eo.getBalType().getValue());
        if (eo.getManagementFreeFlag() != null) criteria.andManagementFreeFlagEqualTo(eo.getManagementFreeFlag());
        if (eo.getAcctLicenseDate() != null) criteria.andAcctLicenseDateEqualTo(eo.getAcctLicenseDate());
        if (eo.getAcctStopPay() != null) criteria.andAcctStopPayEqualTo(eo.getAcctStopPay());
        if (eo.getLoanFundFlag() != null) criteria.andLoanFundFlagEqualTo(eo.getLoanFundFlag());
        if (eo.getImpoundFad() != null) criteria.andImpoundFadEqualTo(eo.getImpoundFad());
        if (eo.getAcctResStatus() != null) criteria.andAcctResStatusEqualTo(eo.getAcctResStatus());
        if (eo.getAcctLicenseNo() != null) criteria.andAcctLicenseNoEqualTo(eo.getAcctLicenseNo());
        if (eo.getParentInternalKey() != null) criteria.andParentInternalKeyEqualTo(eo.getParentInternalKey());
        if (eo.getTaxDiscountMaturityDate() != null) criteria.andTaxDiscountMaturityDateEqualTo(eo.getTaxDiscountMaturityDate());
        if (eo.getFixedCall() != null) criteria.andFixedCallEqualTo(eo.getFixedCall().getValue());
        if (eo.getAcctVerifyResult() != null) criteria.andAcctVerifyResultEqualTo(eo.getAcctVerifyResult().getValue());
        if (eo.getAllDepInd() != null) criteria.andAllDepIndEqualTo(eo.getAllDepInd().getValue());
        if (eo.getOsaFlag() != null) criteria.andOsaFlagEqualTo(eo.getOsaFlag().getValue());
        if (eo.getCaseInvolvedFlag() != null) criteria.andCaseInvolvedFlagEqualTo(eo.getCaseInvolvedFlag());
        if (eo.getAllDraIntBranch() != null) criteria.andAllDraIntBranchEqualTo(eo.getAllDraIntBranch().getValue());
        if (eo.getPartialRenewRoll() != null) criteria.andPartialRenewRollEqualTo(eo.getPartialRenewRoll());
        if (eo.getAutoSettleFlag() != null) criteria.andAutoSettleFlagEqualTo(eo.getAutoSettleFlag());
        if (eo.getAllDraInd() != null) criteria.andAllDraIndEqualTo(eo.getAllDraInd().getValue());
        if (eo.getLineOwnerShip() != null) criteria.andLineOwnerShipEqualTo(eo.getLineOwnerShip());
        if (eo.getInternalKey() != null) criteria.andInternalKeyEqualTo(eo.getInternalKey());
        if (eo.getAcctCloseReason() != null) criteria.andAcctCloseReasonEqualTo(eo.getAcctCloseReason());
        return example;
    }
}